version: '2'

volumes:
  jenkins_home:
    external: true

services:
  jenkins:
    build:
      context: ./jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "50000:50000"
      - "8080:8080"
    restart: always
    container_name: jenkins

  nginx:
    image: nginx
    volumes:
      - ${PWD}/nginx/jenkins.conf:/etc/nginx/conf.d/jenkins.conf
    ports:
      - "80:8000"
    container_name: nginx_jenkins